#  Customer Segmentation Using KMeans and DBSCAN Task


**Dataset:** Customer Segmentation Dataset  
**Algorithms:** KMeans Clustering and DBSCAN  
**Type:** Unsupervised Machine Learning  
**Difficulty:** Intermediate

## 1. Objective

In this assignment, you will implement two clustering algorithms, KMeans and DBSCAN, to identify customer groups based on their characteristics.

You will investigate how clustering algorithms work, how their hyperparameters affect the results, and how to evaluate and visualize the discovered clusters.

## 2. Dataset Description

Use the `customer_segmentation` dataset containing the following three numerical features:

| Feature | Description |
|---|---|
| `Annual Income (k$)` | Customer's annual income in thousands of dollars |
| `Spending Score (1-100)` | Customer's spending score |
| `Age` | Customer's age in years |

The dataset contains 40 customer records and is designed to represent four distinct customer segments.

**Important:** Do not use any predefined cluster labels as input features. The algorithms must discover the groups themselves.

## Part A: Data Preparation

1. Load the dataset into a Pandas DataFrame.
2. Inspect the dataset using:
   - `head()`
   - `info()`
   - `describe()`
   - `isnull().sum()`
3. Check for missing values and duplicate records.
4. Select the three numerical features for clustering.
5. Apply `StandardScaler` to normalize the features before clustering.
6. Explain why feature scaling is important for distance-based algorithms.

**Questions**

- Why is clustering considered an unsupervised learning task?
- Why should we scale the features before applying KMeans and DBSCAN?
- What problems might occur if Annual Income is used without scaling?

## Part B: KMeans Clustering

### Task 1: Implement KMeans

Import `KMeans` from `sklearn.cluster` and implement the algorithm.

Requirements:

1. Train KMeans using `n_clusters=4`.
2. Use `random_state=42` and `n_init=10`.
3. Assign the predicted cluster labels to a new column named `KMeans_Cluster`.
4. Display the number of customers in each cluster.
5. Print the final cluster centers and explain what they represent.

### Task 2: Elbow Method and Inertia

Determine a suitable number of clusters instead of choosing \(K\) arbitrarily.

1. Train KMeans for values of \(K\) from 1 to 10.
2. Calculate the `inertia_` value for every model.
3. Store the values in a list.
4. Plot a graph with:
   - X-axis: Number of clusters \(K\)
   - Y-axis: Inertia
5. Identify the elbow point and select a suitable value of \(K\).

**Questions**

- What does inertia measure?
- Why does inertia decrease when the number of clusters increases?
- Why would choosing \(K\) equal to the number of customers produce a misleadingly low inertia?
- Where is the elbow point in your graph?
- Why did you select this value of \(K\)? Support your answer using the graph and the rate at which inertia decreases.

Do not select \(K=4\) simply because the dataset was designed with four groups. Your selection must be justified using the experiment.

### Task 3: KMeans Visualization

Create the following visualizations:

**1. Two-dimensional scatter plot**

- X-axis: Annual Income
- Y-axis: Spending Score
- Color: KMeans cluster label

**2. Three-dimensional scatter plot**

- X-axis: Annual Income
- Y-axis: Spending Score
- Z-axis: Age
- Color: KMeans cluster label

**3. Elbow plot**

Display inertia against the number of clusters.

Analyze whether the discovered groups are visually separated and whether the 2D and 3D views provide different insights.

## Part C: DBSCAN Clustering

### Task 1: Implement DBSCAN

Import `DBSCAN` from `sklearn.cluster` and apply it to the scaled dataset.

Explore the following parameter combinations:

| Experiment | `eps` | `min_samples` |
|---|---:|---:|
| 1 | 0.3 | 3 |
| 2 | 0.5 | 3 |
| 3 | 0.7 | 3 |
| 4 | 1.0 | 3 |
| 5 | 0.5 | 5 |
| 6 | 0.7 | 5 |
| 7 | 1.0 | 5 |
| 8 | 0.7 | 8 |
| 9 | 1.0 | 8 |

For every experiment:

1. Fit DBSCAN on the scaled features.
2. Assign the results to a column named `DBSCAN_Cluster` or store them separately.
3. Count the number of discovered clusters, excluding the noise label `-1`.
4. Count the number of noise points.
5. Record the results in a summary DataFrame.

Your summary table should contain:

- `eps`
- `min_samples`
- `n_clusters`
- `n_noise_points`

### Task 2: Understand the Parameters

Investigate how the results change when you modify `eps` and `min_samples`.


Support your answers using the results from your experiments.

### Task 3: DBSCAN Visualization

Choose at least three parameter combinations that produce meaningfully different outcomes, if available.

For each selected combination, create:

**1. A 2D scatter plot**
- Annual Income vs. Spending Score
- Color points by their DBSCAN labels
- Display noise points (label `-1`) using a distinct marker or color

**2. A 3D scatter plot**
- Annual Income
- Spending Score
- Age
- Color points by their DBSCAN labels
- Clearly distinguish noise points

Compare the visualizations and explain how the parameter choices affect the number, shape, and separation of clusters.

## Part D: KMeans vs. DBSCAN

Compare the two algorithms using your experimental results.

| Comparison criterion | KMeans | DBSCAN |
|---|---|---|
| Main parameters | `n_clusters` | `eps`, `min_samples` |
| Requires the number of clusters beforehand? | Investigate | Investigate |
| Cluster assignment approach | Investigate | Investigate |
| Can identify noise points? | Investigate | Investigate |
| Sensitivity to feature scaling | Investigate | Investigate |
| Suitable for non-spherical clusters? | Investigate | Investigate |


**Submission requirement:** Submit your completed `.ipynb` notebook with executable code, plots, experimental results, and written explanations. Do not submit plots without the code used to generate them.

In [2]:
import pandas as pd

# Read CSV file
df = pd.read_csv(
    r"Customer Segmentation Dataset.csv"
)

# Display data
df

    Unnamed: 0  Income (k$)  Spending Score (1-100)  Age
0            0           20                      15   22
1            1           22                      18   25
2            2           18                      12   21
3            3           25                      20   28
4            4           23                      14   24
5            5           19                      22   26
6            6           27                      17   23
7            7           21                      10   29
8            8           80                      85   24
9            9           85                      90   27
10          10           78                      82   22
11          11           90                      88   30
12          12           82                      95   26
13          13           88                      80   28
14          14           76                      92   23
15          15           92                      86   31
16          16           18                      85   24
17          17           22                      90   27
18          18           25                      82   21
19          19           20                      95   29
20          20           28                      88   25
21          21           16                      80   23
22          22           24                      92   30
23          23           21                      86   26
24          24           85                      15   45
25          25           90                      20   50
26          26           78                      12   48
27          27           95                      18   55
28          28           82                      22   46
29          29           88                      10   52
30          30           76                      25   43
31          31           92                      14   58
32          32           15                      20   45
33          33           20                      25   50
34          34           25                      15   48
35          35           18                      18   55
36          36           28                      22   46
37          37           22                      10   52
38          38           16                      25   43
39          39           24                      14   58

In [3]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [4]:
df

    Income (k$)  Spending Score (1-100)  Age
0            20                      15   22
1            22                      18   25
2            18                      12   21
3            25                      20   28
4            23                      14   24
5            19                      22   26
6            27                      17   23
7            21                      10   29
8            80                      85   24
9            85                      90   27
10           78                      82   22
11           90                      88   30
12           82                      95   26
13           88                      80   28
14           76                      92   23
15           92                      86   31
16           18                      85   24
17           22                      90   27
18           25                      82   21
19           20                      95   29
20           28                      88   25
21           16                      80   23
22           24                      92   30
23           21                      86   26
24           85                      15   45
25           90                      20   50
26           78                      12   48
27           95                      18   55
28           82                      22   46
29           88                      10   52
30           76                      25   43
31           92                      14   58
32           15                      20   45
33           20                      25   50
34           25                      15   48
35           18                      18   55
36           28                      22   46
37           22                      10   52
38           16                      25   43
39           24                      14   58

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN

In [8]:
# 3. Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)
X_scaled

array([[-0.8563918 , -0.87267537, -1.06677334],
       [-0.79260098, -0.78605747, -0.82432485],
       [-0.92018263, -0.95929327, -1.1475895 ],
       [-0.69691474, -0.7283122 , -0.58187637],
       [-0.76070557, -0.90154801, -0.90514101],
       [-0.88828721, -0.67056693, -0.74350869],
       [-0.63312392, -0.8149301 , -0.98595718],
       [-0.82449639, -1.01703854, -0.5010602 ],
       [ 1.0573329 ,  1.14840903, -0.90514101],
       [ 1.21680995,  1.2927722 , -0.66269253],
       [ 0.99354207,  1.06179113, -1.06677334],
       [ 1.37628701,  1.23502693, -0.42024404],
       [ 1.12112372,  1.43713537, -0.74350869],
       [ 1.31249619,  1.00404586, -0.58187637],
       [ 0.92975125,  1.35051747, -0.98595718],
       [ 1.44007784,  1.17728166, -0.33942788],
       [-0.92018263,  1.14840903, -0.90514101],
       [-0.79260098,  1.2927722 , -0.66269253],
       [-0.69691474,  1.06179113, -1.1475895 ],
       [-0.8563918 ,  1.43713537, -0.5010602 ],
       [-0.60122851,  1.23502693, -0.82432485],
       [-0.98397345,  1.00404586, -0.98595718],
       [-0.72881016,  1.35051747, -0.42024404],
       [-0.82449639,  1.17728166, -0.74350869],
       [ 1.21680995, -0.87267537,  0.79199839],
       [ 1.37628701, -0.7283122 ,  1.1960792 ],
       [ 0.99354207, -0.95929327,  1.03444687],
       [ 1.53576407, -0.78605747,  1.60016001],
       [ 1.12112372, -0.67056693,  0.87281455],
       [ 1.31249619, -1.01703854,  1.35771152],
       [ 0.92975125, -0.58394903,  0.63036606],
       [ 1.44007784, -0.90154801,  1.84260849],
       [-1.01586886, -0.7283122 ,  0.79199839],
       [-0.8563918 , -0.58394903,  1.1960792 ],
       [-0.69691474, -0.87267537,  1.03444687],
       [-0.92018263, -0.78605747,  1.60016001],
       [-0.60122851, -0.67056693,  0.87281455],
       [-0.79260098, -1.01703854,  1.35771152],
       [-0.98397345, -0.58394903,  0.63036606],
       [-0.72881016, -0.90154801,  1.84260849]])

In [ ]:
# 4. Implement KMeans
# TODO

# 5. Calculate inertia for K = 1 to 10
# TODO

# 6. Plot the Elbow Method
# TODO

# 7. Visualize KMeans in 2D and 3D
# TODO

# 8. Experiment with different DBSCAN parameters
# TODO

# 9. Create a comparison table and visualizations
# TODO